on: 

push :
branches : 
- master
name: Production Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:

     - uses: actions/checkout@v2.1.0
     with :
     fetch-depht : 2    
    - name:  FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.xmud6272.odns.fr
        username: makussaaccount@makussa.org
        password: ${{ secrets.ftp_password }}